In [1]:
import pandas as pd
import random

# Data preprocessing

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
diem = pd.read_csv("/content/drive/My Drive/algo_final/diemthi2020.csv")

In [4]:
diem

,Unnamed: 0,Dia,GDCD,Hoa,Li,Ma_mon_ngoai_ngu,Ngoai_ngu,Sinh,Su,Toan,Van,sbd
0,0,7.00,6.50,NaN,NaN,N1,4.2,NaN,4.75,6.4,6.75,18014547
1,1,7.75,7.75,NaN,NaN,N1,2.8,NaN,3.75,7.6,6.00,18014530
2,2,6.50,NaN,NaN,NaN,NaN,NaN,NaN,4.00,4.8,4.75,18014521
3,3,8.00,9.50,NaN,NaN,N1,5.8,NaN,8.25,8.0,7.00,18014517
4,4,NaN,NaN,8.5,8.0,N1,4.0,5.0,NaN,8.2,6.50,18014523
...,...,...,...,...,...,...,...,...,...,...,...,...
870481,870481,6.75,6.25,NaN,NaN,N1,2.0,NaN,3.75,4.6,4.00,17014593
870482,870482,7.50,9.50,NaN,NaN,N1,2.6,NaN,5.50,7.4,8.00,17014597
870483,870483,6.50,8.50,NaN,NaN,N1,6.2,NaN,4.50,8.2,8.75,17014595
870484,870484,7.50,9.00,NaN,NaN,N1,3.6,NaN,4.50,4.6,6.50,17014598
870485,870485,6.50,8.25,NaN,NaN,N1,3.4,NaN,4.25,8.0,7.75,60005601

In [5]:
diem = diem.dropna(subset = ['Hoa', 'Li', 'Toan'])

In [6]:
diem

,Unnamed: 0,Dia,GDCD,Hoa,Li,Ma_mon_ngoai_ngu,Ngoai_ngu,Sinh,Su,Toan,Van,sbd
4,4,NaN,NaN,8.50,8.00,N1,4.0,5.00,NaN,8.2,6.50,18014523
9,9,NaN,NaN,7.75,7.50,N1,4.0,4.50,NaN,9.4,7.00,18014527
11,11,NaN,NaN,7.75,7.25,N1,5.0,4.75,NaN,8.0,6.75,18014515
13,13,NaN,NaN,6.25,5.50,N1,4.6,6.75,NaN,7.6,7.75,18014548
15,15,NaN,NaN,8.25,8.50,N1,5.6,5.00,NaN,8.2,6.75,18014519
...,...,...,...,...,...,...,...,...,...,...,...,...
870471,870471,NaN,NaN,9.00,7.75,N1,3.6,5.25,NaN,9.4,4.75,17014579
870475,870475,NaN,NaN,6.75,5.25,N1,2.4,7.50,NaN,8.8,4.50,17014584
870476,870476,NaN,NaN,4.25,6.50,N1,2.0,4.75,NaN,5.2,6.75,17014592
870477,870477,NaN,NaN,5.75,4.00,N1,5.8,6.50,NaN,8.8,7.75,17014594
870479,870479,NaN,NaN,5.25,7.75,N1,5.8,5.00,NaN,8.0,9.00,17014581

In [7]:
diem.drop(['Unnamed: 0', 'Dia','GDCD','Ma_mon_ngoai_ngu','Sinh','Su','Van'], axis=1, inplace=True)

<ipython-input-7-abf9f9b39a91>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diem.drop(['Unnamed: 0', 'Dia','GDCD','Ma_mon_ngoai_ngu','Sinh','Su','Van'], axis=1, inplace=True)

In [8]:
diem.reset_index()

         index   Hoa    Li  Ngoai_ngu  Toan       sbd
0            4  8.50  8.00        4.0   8.2  18014523
1            9  7.75  7.50        4.0   9.4  18014527
2           11  7.75  7.25        5.0   8.0  18014515
3           13  6.25  5.50        4.6   7.6  18014548
4           15  8.25  8.50        5.6   8.2  18014519
...        ...   ...   ...        ...   ...       ...
291247  870471  9.00  7.75        3.6   9.4  17014579
291248  870475  6.75  5.25        2.4   8.8  17014584
291249  870476  4.25  6.50        2.0   5.2  17014592
291250  870477  5.75  4.00        5.8   8.8  17014594
291251  870479  5.25  7.75        5.8   8.0  17014581

[291252 rows x 6 columns]

In [ ]:
diem['Khoi_A'] = diem['Hoa'] + diem["Li"] + diem['Toan']

<ipython-input-9-4d5e18ca14b8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diem['Khoi_A'] = diem['Hoa'] + diem["Li"] + diem['Toan']

In [ ]:
diem

         Hoa    Li  Ngoai_ngu  Toan       sbd  Khoi_A
4       8.50  8.00        4.0   8.2  18014523   24.70
9       7.75  7.50        4.0   9.4  18014527   24.65
11      7.75  7.25        5.0   8.0  18014515   23.00
13      6.25  5.50        4.6   7.6  18014548   19.35
15      8.25  8.50        5.6   8.2  18014519   24.95
...      ...   ...        ...   ...       ...     ...
870471  9.00  7.75        3.6   9.4  17014579   26.15
870475  6.75  5.25        2.4   8.8  17014584   20.80
870476  4.25  6.50        2.0   5.2  17014592   15.95
870477  5.75  4.00        5.8   8.8  17014594   18.55
870479  5.25  7.75        5.8   8.0  17014581   21.00

[291252 rows x 6 columns]

In [ ]:
uni = pd.read_excel("/content/drive/My Drive/algo_final/diemchuan_demo.xlsx")

In [ ]:
uni

   STT truong  diem_san  chi_tieu
0  1.0   HUST      28.0      20.0
1  2.0    UET      27.2      15.0
2  3.0   PTIT      26.2      30.0
3  4.0    HUS      25.2      15.0
4  5.0   HAUI      24.2      25.0

# Case 1: Sinh vien ghep vao truong tuong ung

In [ ]:
diem_abv_25 = diem[diem['Khoi_A'] > 24]
candiate_case_1 = diem_abv_25.sample(n=170)
candiate_case_1 = candiate_case_1.sort_values(['Khoi_A', 'Toan'], ascending = False)
candiate_case_1 = candiate_case_1.reset_index()
candiate_case_1.drop(['index'],axis=1, inplace=True)

In [ ]:
def create_nv(n,uni):
  nv = []
  for i in range(n):
    randomlist = random.sample(range(len(uni)), 3)
    nv.append(randomlist)
  return nv

In [ ]:
nv = create_nv(170,uni)

In [ ]:
candiate_case_1["STT"] = [i for i in range(len(candiate_case_1))]
candiate_case_1

       Hoa    Li  Ngoai_ngu  Toan       sbd  Khoi_A  STT
0    10.00  8.75        7.4   9.8  41000835   28.55    0
1     9.25  9.50        5.6   9.2  21009093   27.95    1
2     9.00  9.00        5.6   9.6  29002689   27.60    2
3     9.00  8.75        5.4   9.8  27006287   27.55    3
4     9.25  8.75        6.0   9.4   2023832   27.40    4
..     ...   ...        ...   ...       ...     ...  ...
165   7.50  8.00        5.4   8.6  60000204   24.10  165
166   6.75  8.75        8.2   8.6  42012080   24.10  166
167   8.00  7.25        8.6   8.8   2064624   24.05  167
168   7.00  8.25        7.2   8.8   1073017   24.05  168
169   8.00  8.25        5.4   7.8  44010867   24.05  169

[170 rows x 7 columns]

Tao rule Nguyen Vong: NV phia truoc phai la truong co diem chuan cao hon cac NV phia sau, lay lich su cac nam truoc

In [ ]:
candiate_case_1 = candiate_case_1.values.tolist()

In [ ]:
uni_info = uni.values.tolist()

In [ ]:
#tạo dictionary chứa tên trường và các sinh viên ghép vào trường đó
def create_partner(uni_info):
  uni_partner = {}
  for i in range(len(uni_info)):
    uni_partner[i] = []  
  return uni_partner

In [ ]:
uni_info

[[1.0, 'HUST', 28.0, 20.0],
 [2.0, 'UET', 27.2, 15.0],
 [3.0, 'PTIT', 26.2, 30.0],
 [4.0, 'HUS', 25.2, 15.0],
 [5.0, 'HAUI', 24.2, 25.0]]

In [ ]:
def stableMatching(candiate_case_1, nv, uni_info):  
    N = len(candiate_case_1)
    uni_partner = create_partner(uni_info)    
    #Khởi tạo hàm kiểm tra sinh viên được nhận hay chưa
    canMatched = [False for i in range(len(candiate_case_1))]  
    uni_info_cp = uni_info.copy()
    #Tạo vòng lặp để xét tất cả nguyện vọng của thí sinh
    stt_nv = 0
    while stt_nv < len(nv[0]):
                
        #Kiểm tra xem sv đó có ghép cặp hay chưa, nếu chưa thì thực hiện ghép căp, nếu đã có cặp thì xét tiếp sv sau
        for can in range(N):
            if(canMatched[can] == False):                
                #lấy số thứ tự trường là nv thứ i của sinh viên can      
                stt_uni = nv[can][stt_nv]
                #kiểm tra xem trường đó còn chỉ tiêu k, nếu trường đó còn chỉ tiêu thì tiến hành ghép cặp
                if candiate_case_1[can][5]  > uni_info_cp[stt_uni][2]:
                    if uni_info_cp[stt_uni][3] > 0:
                        uni_partner[stt_uni].append(candiate_case_1[can])
                        uni_info_cp[stt_uni][-1] -= 1
                        canMatched[can] = True
                    else:
                    #so sánh điểm thi với sinh viên có điểm thi thấp nhất được nhận vào, nếu > tiến hành ghép cặp, nếu không thì bỏ qua
                        sorted(uni_partner[stt_uni],key=lambda l:l[5], reverse=True)
                        if candiate_case_1[can][5] > uni_partner[stt_uni][-1][5]:         
                        
                            stt = int(uni_partner[stt_uni][-1][6])              
                            del uni_partner[stt_uni][-1]
                            uni_partner[stt_uni].append(candiate_case_1[can])
                            canMatched[stt] = False
                            canMatched[can] = True 
        stt_nv +=1
    return uni_partner

In [ ]:
uni_partner = stableMatching(candiate_case_1, nv, uni_info)

In [ ]:
uni_partner

{0: [],
 1: [],
 2: [[10.0, 8.75, 7.4, 9.8, 41000835.0, 28.55, 0.0],
  [9.5, 8.5, 4.2, 8.8, 27002211.0, 26.8, 11.0],
  [8.75, 9.0, 5.6, 9.0, 2028874.0, 26.75, 14.0],
  [9.0, 8.0, 8.6, 9.4, 26000675.0, 26.4, 21.0],
  [8.75, 8.75, 5.2, 9.4, 15009504.0, 26.9, 10.0],
  [8.25, 9.0, 3.4, 9.4, 28016374.0, 26.65, 16.0],
  [8.5, 8.5, 4.0, 9.4, 12009318.0, 26.4, 20.0],
  [9.25, 8.0, 4.6, 9.8, 33004266.0, 27.05, 7.0],
  [9.0, 9.0, 5.6, 9.0, 18011066.0, 27.0, 8.0],
  [8.75, 8.5, 6.6, 9.0, 33010787.0, 26.25, 26.0]],
 3: [[9.25, 9.5, 5.6, 9.2, 21009093.0, 27.95, 1.0],
  [9.0, 8.75, 5.4, 9.8, 27006287.0, 27.55, 3.0],
  [8.75, 9.0, 8.0, 9.2, 1002217.0, 26.95, 9.0],
  [9.0, 8.75, 5.8, 9.0, 49003152.0, 26.75, 12.0],
  [9.0, 8.75, 7.2, 9.0, 49008662.0, 26.75, 13.0],
  [9.5, 8.25, 8.0, 9.0, 44002091.0, 26.75, 15.0],
  [8.75, 9.0, nan, 8.6, 29030068.0, 26.35, 23.0],
  [8.75, 8.75, 4.4, 8.6, 29015383.0, 26.1, 33.0],
  [8.25, 8.5, 4.4, 9.2, 26006648.0, 25.95, 37.0],
  [9.0, 8.25, 7.8, 8.6, 18015097.0, 25.85, 46.0],
  [8.25, 8.25, 7.2, 9.2, 18017521.0, 25.7, 49.0],
  [8.0, 8.25, 8.8, 9.4, 56004490.0, 25.65, 54.0],
  [8.25, 8.5, 5.8, 8.8, 1020028.0, 25.55, 58.0],
  [8.75, 7.75, 6.2, 9.0, 2066470.0, 25.5, 63.0],
  [8.75, 9.0, 6.2, 9.4, 1017289.0, 27.15, 6.0]],
 4: [[9.0, 9.0, 5.6, 9.6, 29002689.0, 27.6, 2.0],
  [9.5, 9.0, 5.0, 8.8, 25003294.0, 27.3, 5.0],
  [8.25, 8.5, 8.4, 9.8, 25015285.0, 26.55, 19.0],
  [8.5, 9.0, 3.0, 8.8, 38001705.0, 26.3, 25.0],
  [9.25, 8.25, 2.2, 8.6, 22001956.0, 26.1, 32.0],
  [8.75, 8.5, 5.0, 8.8, 22009277.0, 26.05, 34.0],
  [8.5, 8.5, 4.8, 9.0, 28006932.0, 26.0, 35.0],
  [8.75, 8.25, 1.8, 9.0, 1049652.0, 26.0, 36.0],
  [8.5, 8.25, 6.8, 9.2, 26014817.0, 25.95, 38.0],
  [8.25, 8.0, 7.4, 9.6, 57000342.0, 25.85, 41.0],
  [8.75, 7.75, 3.6, 9.2, 21000517.0, 25.7, 51.0],
  [8.75, 8.5, 4.6, 8.4, 16006070.0, 25.65, 57.0],
  [8.5, 8.25, 6.8, 8.8, 53001746.0, 25.55, 59.0],
  [8.25, 8.25, 4.6, 9.0, 40008099.0, 25.5, 62.0],
  [8.5, 8.5, 5.4, 8.4, 1022102.0, 25.4, 71.0],
  [7.75, 8.5, 2.8, 9.0, 29018024.0, 25.25, 76.0],
  [8.0, 8.25, 5.2, 9.0, 33009005.0, 25.25, 77.0],
  [8.75, 7.25, 4.6, 9.2, 25006555.0, 25.2, 82.0],
  [8.0, 8.0, 3.8, 9.2, 25005055.0, 25.2, 83.0],
  [8.25, 8.25, 5.0, 8.6, 19010435.0, 25.1, 88.0],
  [8.75, 6.5, 4.2, 9.8, 15009165.0, 25.05, 92.0],
  [7.75, 8.5, 4.8, 8.8, 55002925.0, 25.05, 93.0],
  [8.25, 8.5, 4.6, 8.2, 28031110.0, 24.95, 98.0],
  [7.75, 8.25, 6.6, 8.8, 27002201.0, 24.8, 104.0],
  [9.25, 8.75, 6.0, 9.4, 2023832.0, 27.4, 4.0]]}